# Generated by Django 3.0.9 on 2020-11-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('productPrice', models.FloatField()),
                ('productDesc', models.CharField(max_length=500)),
                ('productImg', models.URLField(max_length=300)),
            ],
        ),
    ]
