# Generated by Django 3.0.9 on 2020-12-04 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
    ]
